Module File Storing Completed
nlyra/SystemsEngineeringToolkit pull request #164
Opened 2021-06-27 23:02 UTC by DanielMolares

Module Data is now stored in its own folder within the courseID folder. This way the cover image of the course will be easily seen as different from the files stored for the modules. Added a symbol checker, preventing any non-alphanumeric filenames. This may be a little annoying for the user but it'll help prevent the code from being vulnerable to harmful commands.

2021-06-28 13:03 UTC, mbrancato31 requested changes
everything looks good, only some minor changes in the alerts

2021-06-28 13:03 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ModuleCreator.js
> +                    alert('Invalid file type. Please upload an image for which name is alphanumeric and has no spaces.')
should it be PDF? it says image

2021-06-28 13:03 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ModuleCreator.js
> +                    alert('Invalid file type. Please upload an image for which name is alphanumeric and has no spaces.')
here too, should be a file right?

2021-06-28 13:03 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ModuleCreator.js
> +                    alert('Invalid file type. Please upload an image for which name is alphanumeric and has no spaces.')
video

2021-06-28 13:03 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ModuleEditor.js
> +                    alert('Invalid file type. Please upload an image for which name is alphanumeric and has no spaces.')
pdf

2021-06-28 13:03 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ModuleEditor.js
> +                    alert('Invalid file type. Please upload an image for which name is alphanumeric and has no spaces.')
file

2021-06-28 13:03 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ModuleEditor.js
> +                    alert('Invalid file type. Please upload an image for which name is alphanumeric and has no spaces.')
video

2021-06-28 14:24 UTC, collyntheshots approved these changes
Beyond what has been commented on everything looks good

2021-07-07 03:43 UTC, nlyra approved these changes
There are a lot of good fixes in this branch that we will need, but there is still an issue with text modules where if you try to edit a text module it will crash due to some undefined variables.

2021-07-07 03:44 UTC, merged