Made several changes
nlyra/SystemsEngineeringToolkit pull request #201
Opened 2021-07-11 21:31 UTC by DanielMolares

I used this branch to complete the profile changes needed, such as the addition of a close button for the dialog, changing the role description to text rather than an icon that looks like a button, and adding more stats for the admin (since it was lacking the creator stats). 

Because the changes wouldn't be sufficient to warrant another branch, I also added the Scroll for more component to this branch. It's essentially just an icon at the bottom of the dashboard, that will stop appearing if we have listed all courses.

Lastly, I also fixed a minor issue in MyCourses / ManageCourses, where the grid items were appearing too close to each other, thanks to the remove/disenroll button ruining the spacing.

2021-07-11 22:03 UTC, collyntheshots requested changes
Text alignment is a bit off
![Screenshot 2021-07-11 180242](https://user-images.githubusercontent.com/51330857/125211137-46fbfa80-e272-11eb-9fcf-b04bf5161983.png)


My only other suggestion is the delay, if possible, outside of that everything looks good to go

2021-07-12 01:08 UTC, collyntheshots approved these changes

2021-07-12 01:08 UTC, collyntheshots commented
good to go after the changes were made

2021-07-15 18:32 UTC, mbrancato31 requested changes

2021-07-15 18:32 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/Dashboard.js
> +                { totalCourses !== courses.length && (courses.length - totalCourses > cardAmount) &&
not working for last load since courses.length - totalCourses will be less than cardAmount

2021-07-18 17:30 UTC, merged