Bug fix, quiz question viewer
nlyra/SystemsEngineeringToolkit pull request #204
Opened 2021-07-13 17:53 UTC by Michael-Dews

2021-07-14 22:46 UTC, DanielMolares approved these changes
Everything works. Good to push once more reviews come in.

2021-07-15 01:20 UTC, collyntheshots commented
What is this PR even for?

2021-07-15 04:52 UTC, DanielMolares approved these changes
Number of questions to pass still allows negative values. I'd say if there's no way to limit the options to 1 and above, make the component a textbox instead, if it's not too much trouble.

2021-07-15 04:54 UTC, DanielMolares requested changes
Same as comment above; I just accidentally approved instead of requesting change.

2021-07-15 16:50 UTC, collyntheshots approved these changes
Everything seems to be in working order.
I dont know if this is intentional based off the descriptions but I had a PDF module that had been made, I then went to edit the module and changed the "type" to file but did not submit. I then changed it back to PDF and did not need to add a new PDF file to submit my edit

2021-07-15 18:44 UTC, mbrancato31 commented on frontend/toolkit-webapp/src/pages/ManageMyCourses.js
> +                                    : null} */}
if you dont need this, then delete it

2021-07-15 18:46 UTC, mbrancato31 approved these changes

2021-07-15 20:17 UTC, merged